apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-ca
spec:
  serviceAccountName: foo
  containers:
    - name: main
      image: tutum/curl
      command: ["sleep", "999999999"]
    - name: ambassador
      image: luksa/kubectl-proxy:1.6.2