sudo: required
services:
  - docker

before_install:
  - cd udemy-docker-complete-guide/frontend/
  - docker build -t ittus/k8s-training -f Dockerfile.dev .

script:
  - docker run -e CI=true ittus/k8s-training npm run test
# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-northeast-1'
#   name: 'docker-react'
#   app: 'docker-react'
#   env: 'DockerReact-env'
#   bucket_name: 'elasticbeanstalk-ap-northeast-1-825788240328'
#   bucket_path: 'docker-react'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: '$AWS_SECRET_KEY'
